[versions]
agp = "8.12.0"
compiler = "4.16.0"
coordinatorlayout = "1.3.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.12.0"
preference = "1.2.1"
recyclerview = "1.4.0"
roomRuntime = "2.6.1"
viewpager2 = "1.1.0"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

